## 05.07.2020

###############################
## loading libraries
###############################
options(stringsAsFactors = F)
# When loading the packages note that according to
# http://stat545.com/block013_plyr-ddply.html
# we should always load 'plyr' before 'dplyr' when loading/using both.
# install.packages("plyr")
# install.packages("dplyr")
# install.packages("tibble")
# install.packages("tidyr")
# install.packages("lubridate")
# install.packages("ggplot2")
# install.packages("mFilter")
# install.packages("zoo")
# install.packages("miscFuncs")
# install.packages("dynlm")
# install.packages("sandwich")
# install.packages("lmtest")
# install.packages("readxl")
# install.packages("forecast")
# install.packages("stargazer")
# install.packages("vars")
# install.packages("grid")
# install.packages("gridExtra")
# install.packages("rowr")
# install.packages("xts")
# install.packages("dse")
# install.packages("e1071")
# install.packages("Hmisc")
# install.packages("broom")
# install.packages("purrr")
# install.packages("timetk")
# install.packages("sweep")
# install.packages("tseries")
# install.packages("highfrequency")
# install.packages("data.table")
# install.packages("matlib")

library(plyr)
library(dplyr)
library(tibble)
library(tidyr)
library(lubridate)
library(ggplot2)
# theme_set(theme_bw())
library(mFilter)
library(zoo)
library(miscFuncs)
library(dynlm)
library(sandwich)
library(lmtest)
library(readxl)
library(forecast)
library(stargazer)
library(vars)
library(grid)
library(gridExtra)
# library(ggpubr)
# library(rowr)
library(xts)
library(dse)
library(e1071)
library(Hmisc)
# library(broom)
library(purrr)
#library(timetk)
#library(sweep)
library(tseries)
library(highfrequency)
library(gtable)
library(data.table)
library(matlib)
library(RColorBrewer)
